### ISSUE TITLE
Error on Save

### ISSUE THREAD

**Issue by jamesward** [sethvargo/gcs-cacher#2]
```
Step #2 - "save-cache": Already have image (with digest): us-docker.pkg.dev/vargolabs/gcs-cacher/gcs-cacher:0.1
Step #2 - "save-cache": failed to close gcs writer: googleapi: Error 404: Not Found, notFound
```

YAML: https://github.com/GoogleCloudPlatform/multiregion-app-location-demo/blob/master/cloudbuild.yaml

Maybe because I didn't create my bucket?  Can `gcs-cacher` do that for me?

**Comment by jamesward** [comment]
Manually creating the bucket resolved the error but an auto-create option would be really nice. :)

**Comment by sethvargo** [comment]
I updated the docs. There's a lot of variables (went down this path with `berglas bootstrap`) and the permutations end up being vast. Given it's a one-time operation, I think people can use gsutil or the cloud console.
