### ISSUE TITLE
It skips binary files from the cache

### ISSUE THREAD

**Issue by kevinsimper** [sethvargo/gcs-cacher#9]
And node_modules has a lot in `./node_modules/.bin/` which it neatly skips unfortunate, because it is not a regular file.

**Comment by sethvargo** [comment]
Is it a symlink? It's not possible to bundle symlinks into a tarball.

**Comment by kevinsimper** [comment]
@sethvargo I solved it in #10 😄

**Comment by sethvargo** [comment]
See https://github.com/sethvargo/gcs-cacher/pull/10#issuecomment-1585173079
